version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_KEY: base64:SomeRandomKeyForLocalEnv
      APP_DEBUG: 1 # Set to 0 for production
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_SSL_MODE: disable
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "2345:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  npm:
    image: node:18
    container_name: npm_dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173"
    command: >
      bash -c "npm install && npm run dev"

volumes:
  pg_data:
